theme: jekyll-theme-minimal
title: Ben's 3040 assignment
description: 3040 Assignment 2: Applying Etter's Modern Technical Writing principles to host an online resume and README
url: "https://Clarkb2UofM.github.io"
